# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lightning Hacks
email: imesec@ime.usp.br
description: >- # this means to ignore newlines until "baseurl:"
  A iniciativa Lightning Hacks propõe aos estudantes da USP
  o desafio de apresentar uma ideia complexa em apenas 5 minutos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lh.imesec.ime.usp.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
source: src
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
assets:
  js_compressor: nil

permalink: /log/:short_year/:month/:day

exclude: ['node_modules', 'Gemfile.lock', 'webpack']
