FROM python:3.7

RUN python -m ensurepip
RUN pip install pipenv

WORKDIR /data
COPY api/Pipfile api/Pipfile.lock ./
RUN pipenv sync

COPY api ./

EXPOSE 5000
CMD ["pipenv", "run", "gunicorn", "main:app", "-b", "0.0.0.0:5000", "-w", "2"]
