from jekyll/jekyll as build

# Install packages
workdir /app
copy Gemfile Gemfile.lock /app/
copy package.json package-lock.json /app/

# HACK: For some reason, bundle decided to start returning code 15 when running sucessfully for the first time
# and docker considers this a failure, so lets just run it again :)
run bundle install || bundle install
run npm i

# Build
copy . /app
run npx webpack
run mkdir /app/_site
run mkdir /app/.jekyll-cache
run JEKYLL_ENV=production jekyll build

entrypoint ["/bin/bash"]

# Strip build image & serve
from ubuntu:latest as server

run apt-get update
run DEBIAN_FRONTEND=noninteractive apt-get install -y npm
run npm i -g serve
copy --from=build /app/_site /app/
workdir /app
expose 5000
cmd ["serve", "-p", "5000"]
