version: "3"

services:
  web:
    container_name: lightning_web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "4455:5000"

  api:
    container_name: lightning_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "4456:5000"
